name: template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
