name: template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State management
  bloc:
  flutter_bloc:

  #Network
  dio:
  graphql_flutter:
  http:

  #Dependency injection
  get_it:

  #Local storage
  shared_preferences:
  flutter_secure_storage:

  #Routing
  go_router:

  #Localization
  flutter_localizations:
    sdk: flutter

  #UI
  intl:
  cached_network_image:

  #Utils
  dartz:
  equatable:
  json_annotation:

  #External
  url_launcher:

  #Testing
  mockito:
  bloc_test:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  json_serializable:
  build_runner:

flutter:
  uses-material-design: true
